language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - composer selfupdate
  - composer install --dev --prefer-source

script: vendor/bin/phpunit

